import { type ImgHTMLAttributes } from "react";

/**
 * Drop-in replacement for `<img>` that emits a `<picture>` with the matching
 * WebP variant + the original JPG/PNG fallback.
 *
 * Assumes a corresponding `.webp` exists alongside the JPG/PNG (generated by
 * `scripts/optimize-images.mjs`). External URLs (http/https) pass through
 * unchanged — only local `/images/...` paths get the WebP source.
 *
 * Usage:
 *   <Picture src="/images/foo.jpg" alt="..." width={800} height={600} />
 *
 * All extra props (className, loading, fetchPriority, onError, etc.) pass
 * through to the inner `<img>`.
 */
type Props = Omit<ImgHTMLAttributes<HTMLImageElement>, "src"> & {
  src: string;
};

/** Rewrite a local .jpg/.png path to a sibling of the given format.
 *  Returns null for remote URLs or paths that are already webp/avif. */
function toExt(src: string, ext: "webp" | "avif"): string | null {
  if (/^https?:/.test(src)) return null;
  if (/\.(webp|avif)(\?|$)/i.test(src)) return null;
  if (!/\.(jpe?g|png)(\?|$)/i.test(src)) return null;
  return src.replace(/\.(jpe?g|png)(\?|$)/i, `.${ext}$2`);
}

const Picture = ({ src, loading, ...imgProps }: Props) => {
  // AVIF (~30% smaller than WebP) is offered first; the browser picks the
  // first <source> it can decode, falling back to WebP, then the original
  // raster <img>. Both siblings are generated by scripts/optimize-images.mjs.
  const avif = toExt(src, "avif");
  const webp = toExt(src, "webp");
  // Default `loading="lazy"` for below-fold images. Above-fold callers (hero,
  // header logo) that need eager loading pass `fetchPriority="high"`
  // and/or `loading="eager"` explicitly. Aligns with Google's lazy-loading
  // guidance (developers.google.com/search/docs/crawling-indexing/javascript/lazy-loading).
  const effectiveLoading = loading ?? "lazy";
  if (!webp && !avif) {
    return <img src={src} loading={effectiveLoading} {...imgProps} />;
  }
  return (
    <picture>
      {avif && <source srcSet={avif} type="image/avif" />}
      {webp && <source srcSet={webp} type="image/webp" />}
      <img src={src} loading={effectiveLoading} {...imgProps} />
    </picture>
  );
};

export default Picture;
