import { type ImgHTMLAttributes } from "react";

/**
 * Drop-in replacement for `<img>` that emits a `<picture>` with the matching
 * WebP variant + the original JPG/PNG fallback.
 *
 * Assumes a corresponding `.webp` exists alongside the JPG/PNG (generated by
 * `scripts/optimize-images.mjs`). External URLs (http/https) pass through
 * unchanged — only local `/images/...` paths get the WebP source.
 *
 * Usage:
 *   <Picture src="/images/foo.jpg" alt="..." width={800} height={600} />
 *
 * All extra props (className, loading, fetchPriority, onError, etc.) pass
 * through to the inner `<img>`.
 */
type Props = Omit<ImgHTMLAttributes<HTMLImageElement>, "src"> & {
  src: string;
};

function toWebp(src: string): string | null {
  // Skip remote URLs and already-webp paths.
  if (/^https?:/.test(src)) return null;
  if (/\.webp(\?|$)/i.test(src)) return null;
  if (!/\.(jpe?g|png)(\?|$)/i.test(src)) return null;
  return src.replace(/\.(jpe?g|png)(\?|$)/i, ".webp$2");
}

const Picture = ({ src, ...imgProps }: Props) => {
  const webp = toWebp(src);
  if (!webp) {
    // Remote / unsupported source — render plain <img>.
    return <img src={src} {...imgProps} />;
  }
  return (
    <picture>
      <source srcSet={webp} type="image/webp" />
      <img src={src} {...imgProps} />
    </picture>
  );
};

export default Picture;
