import { type ImgHTMLAttributes } from "react";

/**
 * Drop-in replacement for `<img>` that emits a `<picture>` with the matching
 * WebP variant + the original JPG/PNG fallback.
 *
 * Assumes a corresponding `.webp` exists alongside the JPG/PNG (generated by
 * `scripts/optimize-images.mjs`). External URLs (http/https) pass through
 * unchanged — only local `/images/...` paths get the WebP source.
 *
 * Usage:
 *   <Picture src="/images/foo.jpg" alt="..." width={800} height={600} />
 *
 * All extra props (className, loading, fetchPriority, onError, etc.) pass
 * through to the inner `<img>`.
 */
// width + height are REQUIRED (not the optional versions from
// ImgHTMLAttributes): the browser uses them to reserve layout space and
// compute aspect-ratio before the image loads, preventing CLS. Making them
// mandatory turns a missing dimension into a compile error instead of a
// silent layout shift in production.
type Props = Omit<ImgHTMLAttributes<HTMLImageElement>, "src" | "width" | "height"> & {
  src: string;
  width: number | string;
  height: number | string;
};

/** Rewrite a local .jpg/.png path to a sibling of the given format.
 *  Returns null for remote URLs or paths that are already webp/avif. */
function toExt(src: string, ext: "webp" | "avif"): string | null {
  if (/^https?:/.test(src)) return null;
  if (/\.(webp|avif)(\?|$)/i.test(src)) return null;
  if (!/\.(jpe?g|png)(\?|$)/i.test(src)) return null;
  return src.replace(/\.(jpe?g|png)(\?|$)/i, `.${ext}$2`);
}

const Picture = ({ src, loading, fetchPriority, ...imgProps }: Props) => {
  // AVIF (~30% smaller than WebP) is offered first; the browser picks the
  // first <source> it can decode, falling back to WebP, then the original
  // raster <img>. Both siblings are generated by scripts/optimize-images.mjs.
  const avif = toExt(src, "avif");
  const webp = toExt(src, "webp");
  // Default `loading="lazy"` for below-fold images. Above-fold callers (hero,
  // header logo) that need eager loading pass `fetchPriority="high"`
  // and/or `loading="eager"` explicitly. Aligns with Google's lazy-loading
  // guidance (developers.google.com/search/docs/crawling-indexing/javascript/lazy-loading).
  const effectiveLoading = loading ?? "lazy";

  // React 18 does not recognise the camelCase `fetchPriority` prop:
  // react-dom/server passes it through into the HTML as an attribute, while
  // the client renderer drops it. The hydrated DOM therefore disagrees with
  // the prerendered HTML on this one attribute, and React responds by
  // throwing away the whole server tree and re-rendering on the client
  // (errors #418 / #423) — which forfeits the LCP benefit the prerender
  // exists to provide. Emitting the lowercase attribute, exactly as React's
  // own warning instructs, makes both renderers agree.
  const priorityAttr = (fetchPriority
    ? { fetchpriority: fetchPriority }
    : {}) as Record<string, string>;
  if (!webp && !avif) {
    return <img src={src} loading={effectiveLoading} {...priorityAttr} {...imgProps} />;
  }
  return (
    <picture>
      {avif && <source srcSet={avif} type="image/avif" />}
      {webp && <source srcSet={webp} type="image/webp" />}
      <img src={src} loading={effectiveLoading} {...priorityAttr} {...imgProps} />
    </picture>
  );
};

export default Picture;
